"""Host Security ID (HSI) audit and hardening command module."""

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

SYSFS_MEM_SLEEP_DEFAULT = "/sys/power/mem_sleep"
PROC_SWAPS_DEFAULT = "/proc/swaps"


def generate_zram_config(ram_fraction: str = "ram / 2", max_mb: int = 8192) -> str:
    """Generate systemd-zram-generator configuration string."""
    return (
        "# Generated by osm hsi harden\n"
        "[zram0]\n"
        f"zram-size = min({ram_fraction}, {max_mb})\n"
        "compression-algorithm = zstd\n"
        "swap-priority = 100\n"
    )


def check_sleep_state(sysfs_path: str = SYSFS_MEM_SLEEP_DEFAULT) -> dict[str, Any]:
    """Inspect current ACPI mem_sleep state from sysfs."""
    node = Path(sysfs_path)
    if not node.is_file():
        return {
            "current": "unsupported",
            "available": [],
            "hardened": False,
            "error": f"Node {sysfs_path} not found",
        }
    try:
        raw = node.read_text().strip()
        tokens = raw.split()
        current = "unknown"
        available = []
        for t in tokens:
            if t.startswith("[") and t.endswith("]"):
                current = t.strip("[]")
                available.append(current)
            else:
                available.append(t)
        return {
            "current": current,
            "available": available,
            "hardened": current == "s2idle",
        }
    except Exception as exc:
        return {
            "current": "error",
            "available": [],
            "hardened": False,
            "error": str(exc),
        }


def check_active_swap(proc_swaps_path: str = PROC_SWAPS_DEFAULT) -> dict[str, Any]:
    """Inspect active system swap devices and check for unencrypted partitions."""
    node = Path(proc_swaps_path)
    if not node.is_file():
        return {
            "zram_active": False,
            "unencrypted_disk_swap": False,
            "hardened": False,
            "devices": [],
        }
    try:
        lines = node.read_text().strip().splitlines()
        devices = []
        zram_active = False
        unencrypted_disk_swap = False

        for line in lines[1:]:
            parts = line.split()
            if not parts:
                continue
            dev = parts[0]
            dev_type = parts[1] if len(parts) > 1 else ""
            devices.append({"device": dev, "type": dev_type})
            if "zram" in dev:
                zram_active = True
            elif dev.startswith(("/dev/nvme", "/dev/sd", "/dev/vd", "/swapfile")):
                unencrypted_disk_swap = True

        hardened = zram_active and not unencrypted_disk_swap
        return {
            "zram_active": zram_active,
            "unencrypted_disk_swap": unencrypted_disk_swap,
            "hardened": hardened,
            "devices": devices,
        }
    except Exception as exc:
        return {
            "zram_active": False,
            "unencrypted_disk_swap": False,
            "hardened": False,
            "error": str(exc),
            "devices": [],
        }


def check_fwupd_dbx() -> dict[str, Any]:
    """Check fwupd security status for UEFI dbx and firmware."""
    if not shutil.which("fwupdmgr"):
        return {
            "supported": False,
            "reason": "fwupdmgr binary not found in PATH",
        }
    try:
        res = subprocess.run(
            ["fwupdmgr", "security", "--json"],
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
        if res.returncode == 0 and res.stdout:
            data = json.loads(res.stdout)
            return {"supported": True, "data": data}
        return {"supported": True, "raw_output": res.stdout or res.stderr}
    except Exception as exc:
        return {"supported": False, "error": str(exc)}


def audit_hsi_posture() -> dict[str, Any]:
    """Aggregate complete HSI device posture telemetry."""
    sleep_info = check_sleep_state()
    swap_info = check_active_swap()
    fwupd_info = check_fwupd_dbx()

    is_hardened = sleep_info.get("hardened", False) and swap_info.get("hardened", False)

    return {
        "overall_status": "hardened" if is_hardened else "needs_hardening",
        "sleep_state": sleep_info,
        "swap": swap_info,
        "fwupd": fwupd_info,
    }


def run_hsi(args: list[str]) -> int:
    """Execute HSI audit or hardening CLI command."""
    parser = argparse.ArgumentParser(
        prog="osm hsi",
        description="Host Security ID (HSI) device audit and hardening engine.",
    )
    subparsers = parser.add_subparsers(dest="action", help="HSI actions")

    audit_p = subparsers.add_parser("audit", help="Audit current HSI security posture")
    audit_p.add_argument("--json", action="store_true", help="Output results in JSON format")

    apply_p = subparsers.add_parser("apply", help="Apply HSI hardening remediations")
    apply_p.add_argument("--dry-run", action="store_true", help="Simulate remediation actions")

    if not args:
        args = ["audit"]

    parsed = parser.parse_args(args)

    if parsed.action == "audit":
        telemetry = audit_hsi_posture()
        if getattr(parsed, "json", False):
            print(json.dumps(telemetry, indent=2))
        else:
            print("=== Host Security ID (HSI) Posture Audit ===")
            print(f"Overall Status : {telemetry['overall_status'].upper()}")
            print(f"Sleep Mode     : {telemetry['sleep_state'].get('current')} (Hardened: {telemetry['sleep_state'].get('hardened')})")
            print(f"Swap Engine    : zRAM Active={telemetry['swap'].get('zram_active')}, Unencrypted Disk={telemetry['swap'].get('unencrypted_disk_swap')} (Hardened: {telemetry['swap'].get('hardened')})")
            print(f"Firmware Engine: fwupdmgr available={telemetry['fwupd'].get('supported')}")
        return 0

    if parsed.action == "apply":
        if getattr(parsed, "dry_run", False):
            print("[DRY-RUN] Would install systemd-zram-generator and configure /etc/systemd/zram-generator.conf")
            print("[DRY-RUN] Would update /etc/default/grub with mem_sleep_default=s2idle and run update-grub")
            print("[DRY-RUN] Would invoke fwupdmgr refresh and fwupdmgr update")
            return 0

        print("[INFO] Invoking scripts/hsi-harden.sh for system-level remediation...")
        script_path = Path(__file__).resolve().parents[2] / "scripts" / "hsi-harden.sh"
        if not script_path.is_file():
            print(f"[ERROR] Playbook script not found at {script_path}")
            return 1

        cmd = ["sudo", str(script_path)] if os.geteuid() != 0 else [str(script_path)]
        res = subprocess.run(cmd, check=False)
        return res.returncode

    return 0
