"""Memory management and zRAM optimization subsystem."""
from os_manager.memory.psi_daemon import (
    MitigationTier,
    PsiMetrics,
    PsiMonitorEngine,
    PsiReading,
    PsiSubsystem,
    PsiThresholds,
    audit_psi_telemetry,
    collect_psi_metrics,
    compact_zram_devices,
    generate_psi_systemd_unit,
    manage_psi_daemon,
    parse_psi_file,
    parse_psi_line,
    trigger_critical_cache_drop,
    trigger_mglru_kick,
)
from os_manager.memory.zram import (
    CANONICAL_ZRAM_CONF,
    CANONICAL_ZRAM_DEVICE,
    CANONICAL_ZRAM_GENERATOR_PKG,
    CONFLICTING_ZRAM_SERVICES,
    ConflictingServiceStatus,
    ZramAuditReport,
    audit_zram_system,
    generate_canonical_zram_conf,
    remediate_zram_conflicts,
    unmask_zram_service,
)

__all__ = [
    "CANONICAL_ZRAM_CONF",
    "CANONICAL_ZRAM_DEVICE",
    "CANONICAL_ZRAM_GENERATOR_PKG",
    "CONFLICTING_ZRAM_SERVICES",
    "ConflictingServiceStatus",
    "ZramAuditReport",
    "audit_zram_system",
    "generate_canonical_zram_conf",
    "remediate_zram_conflicts",
    "unmask_zram_service",
    "PsiReading",
    "PsiMetrics",
    "PsiThresholds",
    "PsiSubsystem",
    "MitigationTier",
    "parse_psi_line",
    "parse_psi_file",
    "collect_psi_metrics",
    "compact_zram_devices",
    "trigger_mglru_kick",
    "trigger_critical_cache_drop",
    "generate_psi_systemd_unit",
    "manage_psi_daemon",
    "audit_psi_telemetry",
    "PsiMonitorEngine",
]
